spring:
  application:
    name: Time Trial API

  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: dc1
    keyspace-name: time_trial
    schema-action: none
    request:
      consistency: QUORUM

time-trial:
  secret-keys:
    tempo-minimo-volta: 2000
    tempo-maximo-volta: 30000

mqtt:
  broker: ssl://12f590a554fc4cfda1e6e2edd8381c84.s1.eu.hivemq.cloud:8883
  client-id: spring-backend-timetrial-${random.uuid}
  topic: senai/timetrial/corrida/sensor
  username: ${USER_HIVEMQ}
  password: ${PASSWORD_HIVEMQ}


management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      logback: true
      all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true